### ISSUE TITLE
"422 Only the first 1000 search results are available" for GitHub issue interactions

### ISSUE THREAD

**Issue by bcmills** [stamblerre/work-stats#7]
I got this output from `work-stats` for a ~1yr window:

<pre>
~/src/github.com/stamblerre/work-stats$ work-stats --username=bcmills --email=bcmills@google.com --since=2019-02-01
2020/02/26 13:28:28 Loading data from log *maintner.netMutSource ...
2020/02/26 13:28:28 Downloading 3565 bytes of https://maintner.golang.org/logs/63 ...
2020/02/26 13:28:28 wrote /usr/local/google/home/bcmills/.cache/golang-maintner/0063.growing.mutlog
2020/02/26 13:28:42 Reloaded data from log *maintner.netMutSource.
2020/02/26 13:28:42 Wrote output to /tmp/work-stats048958562/golang-issues.csv.
2020/02/26 13:28:42 Wrote output to /tmp/work-stats048958562/golang-authored.csv.
2020/02/26 13:28:42 Wrote output to /tmp/work-stats048958562/golang-reviewed.csv.
<b>2020/02/26 13:29:12 GET https://api.github.com/search/issues?page=11&per_page=100&q=involves%3Abcmills+updated%3A%3E%3D2019-02-01: 422 Only the first 1000 search results are available []</b>
</pre>

The 1000-result error seems unfortunate. Any ideas for how to work around it?

**Comment by stamblerre** [comment]
Thanks for reporting this! I know it's a bit late, but I think that https://github.com/stamblerre/work-stats/commit/c3871b1d1b1741234c292daff86654208bfd8e4e should handle it.
